SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) TOTAL_SALES
FROM BOOK a
JOIN AUTHOR b
ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES c
ON a.BOOK_ID = c.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY 1,2,3
ORDER BY 1 , 3 DESC