SELECT b.USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_PRICE
FROM (SELECT * FROM USED_GOODS_BOARD 
      WHERE STATUS =  'DONE') a
JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
GROUP BY b.USER_ID, NICKNAME
HAVING TOTAL_PRICE >= 700000
ORDER BY TOTAL_PRICE;